# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YahooWeatherAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'OAuthSwift', '~> 1.2.0'
  pod 'Dropper', '~> 2.7'
  pod 'ReachabilitySwift'

end
